json.id boat.id
json.nome boat.nome
json.descrizione boat.descrizione
json.tipo boat.tipo
json.prezzo boat.prezzo
json.lunghezza boat.lunghezza
json.anno boat.anno
json.porto boat.porto
json.immagine url_for(boat.immagine)
json.url boat_url(boat)